apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: mongo1
spec:
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  capacity:
    storage: 1Gi
  nfs:
    path: /mnt/k8sMount/mongo1
    server: 167.254.204.230

