apiVersion: v1
kind: Service
metadata:
  name: mongo1
  labels:
    app: mongo1
spec:
  type: NodePort
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
    nodePort: 30019
  selector:
    app: mongo1
