apiVersion: v1
kind: Service
metadata:
  name: mongodb-siteb-shard3-headless-service
  namespace: daemonsl
  labels:
    name: mongodb-siteb-shard3
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30018
  #clusterIP: None
  selector:
    role: mongodb-siteb-shard3
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-sietb-shard3
  namespace: daemonsl
spec:
  selector:
    matchLabels:
      role: mongodb-siteb-shard3 # has to match .spec.template.metadata.labels
  serviceName: mongodb-siteb-shard3-headless-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-siteb-shard3
        tier: maindb
        replicaset: Shard3
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - Shard3
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-siteb-shard3-container
          image: mongo:4.0
          imagePullPolicy: IfNotPresent
          command:
            - "mongod"
            - "--port"
            - "27017"
            - "--bind_ip_all"
            - "--replSet"
            - "Shard3"
            - "--dbpath"
            - "/mongo-disk"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-shard3-persistent-storage-claim
              mountPath: /mongo-disk
  volumeClaimTemplates:
  - metadata:
      name: mongo-shard3-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
