kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo3-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: mongo3

