apiVersion: v1
kind: Service
metadata:
  name: mongo2
  labels:
    app: mongo2
spec:
  type: NodePort
  ports:
  - name: mongo
    port: 40002
    targetPort: 27017
    nodePort: 30019
  selector:
    app: mongo2
