apiVersion: v1
kind: Service
metadata:
  name: mongodb-shardx-headless-service
  namespace: config-servers
  labels:
    name: mongodb-shardx
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongodb-shardx
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-shardx
  namespace: config-servers
spec:
  selector:
    matchLabels:
      role: mongodb-shardx # has to match .spec.template.metadata.labels
  serviceName: mongodb-shardx-headless-service
  replicas: 1
  template:
    metadata:
      labels:
        role: mongodb-shardx
        tier: maindb
        replicaset: Shardx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongodb-shardx-container
          image: mongo
          command:
            - "mongod"
            - "--port"
            - "27017"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "ShardX"
            - "--dbpath"
            - "/mongo-disk"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-shardx-persistent-storage-claim
              mountPath: /mongo-disk
  volumeClaimTemplates:
  - metadata:
      name: mongo-shardx-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
