apiVersion: v1
kind: Service
metadata:
  name: mongo1-6
  labels:
    name: mongo1-6
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30023
  selector:
    role: mongo1-6

