apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo1-6
spec:
  selector:
    matchLabels:
      role: mongo1-6 # has to match .spec.template.metadata.labels
  serviceName: mongo1-6
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo1-6
        tier: maindb
        replicaset: rs0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - rs0
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo1-6-container
          image: mongo:4.0
          imagePullPolicy: IfNotPresent
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "rs0"
            - "--smallfiles"
            - "--noprealloc"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo1-6-persistent-storage-claim
              mountPath: /mongo-disk
  volumeClaimTemplates:
  - metadata:
      name: mongo1-6-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
