apiVersion: v1
kind: Service
metadata:
  name: mongo2
  labels:
    name: mongo2
spec:
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30019
  selector:
    role: mongo2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo2
spec:
  selector:
    matchLabels:
      role: mongo2 # has to match .spec.template.metadata.labels
  serviceName: mongo2
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo2
        tier: maindb
        replicaset: rs0
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - rs0
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo2-container
          image: mongo:4.0
          imagePullPolicy: IfNotPresent
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "rs0"
            - "--smallfiles"
            - "--noprealloc"
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo2-persistent-storage-claim
              mountPath: /mongo-disk
  volumeClaimTemplates:
  - metadata:
      name: mongo2-persistent-storage-claim
      annotations:
        volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
