apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cfgsvr2
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"

  creationTimestamp: null
  labels:
    io.kompose.service: cfgsvr2
  name: cfgsvr2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
