apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cfgsvr1
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
  creationTimestamp: null
  labels:
    io.kompose.service: cfgsvr1
  name: cfgsvr1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
