apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cfgsvr2
  name: cfgsvr2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cfgsvr2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cfgsvr2
    spec:
      containers:
        - args:
            - mongod
            - --configsvr
            - --replSet
            - cfgrs
            - --port
            - "27017"
            - --dbpath
            - /data/db
            - --bind_ip
            - 0.0.0.0
          image: mongo:4.0
          imagePullPolicy: IfNotPresent
          name: cfgsvr2
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: cfgsvr2
      restartPolicy: Always
      volumes:
        - name: cfgsvr2
          persistentVolumeClaim:
            claimName: cfgsvr2
status: {}
