
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-cluster
spec:
  #clusterIP: None
  type: NodePort
  selector:
    app: es-cluster
  ports:
  - name: transport
    port: 9300
    nodePort: 30035
