apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-loadbalancer
spec:
  type: NodePort
  selector:
    app: es-cluster
  ports:
  - name: http
    port: 9200
    protocol: TCP
    nodePort: 30026
